"""Idempotent detached final dispatch; no final input acquisition or answer editing."""
import argparse,datetime,hashlib,json,os,re,shutil,signal,socket,subprocess,sys,tarfile,time,urllib.request
from pathlib import Path
BASE=Path('/home/shadeform/machinekind-matura-pawel-20260927')
STAGE=BASE/'manual-final-stage'
BINARY=BASE/'runtime/bin/ollama'
def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for b in iter(lambda:f.read(8*1024*1024),b''):h.update(b)
 return h.hexdigest()
def read(p):return json.loads(p.read_text(encoding='utf8'))
def atomic(p,x):
 q=p.with_suffix(p.suffix+'.tmp');q.write_text(json.dumps(x,indent=2)+'\n');os.replace(q,p)
def root(run):
 if not re.fullmatch(r'[0-9]{8}T[0-9]{6}-[a-f0-9]{8}',run):raise ValueError('Invalid run ID')
 return STAGE/'runs'/run
def api(port):
 opener=urllib.request.build_opener(urllib.request.ProxyHandler({}));return json.load(opener.open(f'http://127.0.0.1:{port}/api/ps',timeout=3))
def ticks(pid):return Path(f'/proc/{pid}/stat').read_text().split(') ',1)[1].split()[19]
def stage(run,archive_sha,manifest_sha):
 r=root(run);archive=STAGE/'incoming'/(run+'.tar.gz');assert sha(archive)==archive_sha
 if r.exists() and (r/'stage.json').exists():
  assert sha(r/'package/launch.json')==manifest_sha,'Existing run identity mismatch';return {'status':'EXISTS','run_id':run}
 if r.exists():
  assert not (r/'dispatch.json').exists(),'Never restage a dispatched run'
  assert {x.name for x in r.iterdir()}<={'package','models'},'Unexpected incomplete staging contents'
 r.mkdir(parents=True,exist_ok=True)
 with tarfile.open(archive) as t:
  for m in t.getmembers():
   p=Path(m.name)
   assert not p.is_absolute() and '..' not in p.parts and not m.issym() and not m.islnk() and (m.isfile() or m.isdir()),'Unsafe archive member'
  t.extractall(r)
 p=r/'package';assert sha(p/'launch.json')==manifest_sha
 m=read(p/'launch.json');assert m['cache']==str(r/'models') and m['binary']==str(BINARY) and m['lock']==str(BASE/'final-offline.lock')
 # Immutable base is never served. Each run receives five hardlinked members;
 # metadata generated by Ollama belongs only to that run.
 for item in read(STAGE/'weights-proof.json')['inventory']['files']:
  src=STAGE/'models-base'/item['path'];dest=r/'models'/item['path'];dest.parent.mkdir(parents=True,exist_ok=True)
  if dest.exists():assert dest.stat().st_size==item['bytes'] and sha(dest)==item['sha256'],'Interrupted-stage model mismatch'
  else:
   try:os.link(src,dest)
   except OSError:shutil.copyfile(src,dest)
 check=subprocess.run([sys.executable,'-B',str(p/'run_recovery_package.py'),str(p)],capture_output=True,text=True)
 assert check.returncode==0,check.stderr
 atomic(r/'stage.json',{'run_id':run,'archive_sha256':archive_sha,'manifest_sha256':manifest_sha,'preflight':check.stdout,'model_calls':0})
 return {'status':'STAGED','run_id':run,'preflight':check.stdout}
def start(run):
 r=root(run);assert (r/'stage.json').exists()
 marker=r/'dispatch.json'
 if marker.exists():return {'status':'ALREADY_DISPATCHED','dispatch':read(marker)}
 m=read(r/'package/launch.json');end=datetime.datetime.fromisoformat(m['deadline_utc']).timestamp();assert time.time()+20<end
 # O_EXCL is the dispatch authority, including concurrent Resume invocations.
 try:
  with marker.open('x') as f:json.dump({'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'manifest_sha256':sha(r/'package/launch.json')},f);f.flush();os.fsync(f.fileno())
 except FileExistsError:return {'status':'ALREADY_DISPATCHED','dispatch':read(marker)}
 try:
  with (r/'operator.log').open('xb') as log:
   child=subprocess.Popen([sys.executable,'-B',str(Path(__file__).resolve()),'run',run],stdin=subprocess.DEVNULL,stdout=log,stderr=subprocess.STDOUT,start_new_session=True)
 except Exception as exc:
  atomic(r/'spawn-error.json',{'error':repr(exc),'automatic_retry':False});raise
 atomic(r/'supervisor.json',{'pid':child.pid,'ticks':ticks(child.pid)})
 return {'status':'DISPATCHED','pid':child.pid}
def run(run):
 r=root(run);p=r/'package';server=None;identity=None;rc=None;error=None;began=time.time()
 try:
  gpu=subprocess.check_output(['nvidia-smi','--query-compute-apps=pid,process_name,used_memory','--format=csv,noheader'],text=True);assert not gpu.strip(),gpu
  assert not api(11434)['models'],'Original service has a loaded model'
  with socket.socket() as sock:assert sock.connect_ex(('127.0.0.1',11436))!=0,'Sentinel port already in use'
  home=r/'idle-home';cache=r/'idle-empty-models';home.mkdir();cache.mkdir()
  env={'PATH':os.environ['PATH'],'HOME':str(home),'OLLAMA_HOST':'127.0.0.1:11436','OLLAMA_MODELS':str(cache),'OLLAMA_NO_CLOUD':'1','OLLAMA_NUM_PARALLEL':'1','OLLAMA_MAX_LOADED_MODELS':'1'}
  with (r/'idle-server.log').open('xb') as log:server=subprocess.Popen([str(BINARY),'serve'],env=env,stdout=log,stderr=subprocess.STDOUT,start_new_session=True)
  identity={'pid':server.pid,'ticks':ticks(server.pid),'executable':str(BINARY)};atomic(r/'sentinel-identity.json',identity)
  for _ in range(100):
   try:assert not api(11436)['models'];break
   except OSError:assert server.poll() is None;time.sleep(.2)
  else:raise RuntimeError('Owned sentinel did not start')
  rc=subprocess.call(['bash',str(p/'operator_recovery.sh'),str(p),'--execute'])
 except BaseException as exc:error=type(exc).__name__+': '+str(exc)
 finally:
  cleanup={'started':server is not None,'stopped':False}
  if server:
   if server.poll() is None:
    assert ticks(server.pid)==identity['ticks'] and Path(f'/proc/{server.pid}/exe').resolve()==BINARY.resolve(),'Sentinel ownership changed'
    os.killpg(server.pid,signal.SIGTERM)
    try:server.wait(timeout=3)
    except subprocess.TimeoutExpired:os.killpg(server.pid,signal.SIGKILL);server.wait(timeout=3)
   cleanup.update(stopped=True,returncode=server.returncode)
  gpu=subprocess.check_output(['nvidia-smi','--query-compute-apps=pid,process_name,used_memory','--format=csv,noheader'],text=True)
  answer=p/'results/answers.json'
  terminal={'run_id':run,'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'operator_returncode':rc,'error':error,'wall_seconds':time.time()-began,'sentinel_cleanup':cleanup,'gpu_after':gpu,'answers_present':answer.exists(),'answers_sha256':sha(answer) if answer.exists() else None}
  atomic(r/'terminal.json',terminal)
  archive=r/'terminal.tar.gz'
  with tarfile.open(archive,'x:gz') as t:
   t.add(p,arcname='package')
   for name in ('terminal.json','stage.json','dispatch.json','supervisor.json','operator.log','sentinel-identity.json'):
    if (r/name).exists():t.add(r/name,arcname=name)
  atomic(r/'backup.json',{'sha256':sha(archive),'bytes':archive.stat().st_size})
 return terminal
def status(run):
 r=root(run)
 if not r.exists():return {'status':'NOT_STAGED','run_id':run,'utc':datetime.datetime.now(datetime.timezone.utc).isoformat()}
 result={'run_id':run,'status':'STAGED','utc':datetime.datetime.now(datetime.timezone.utc).isoformat()}
 if (r/'dispatch.json').exists():result.update(status='RUNNING',dispatch=read(r/'dispatch.json'))
 if (r/'terminal.json').exists():result.update(status='FINALIZING_BACKUP',terminal=read(r/'terminal.json'))
 if (r/'backup.json').exists():result.update(status='TERMINAL',backup=read(r/'backup.json'))
 export_status=r/'package/results/deadline-rag-status.json'
 if export_status.exists():
  items=read(export_status)['items'];result['answer_summary']={'original_items':len(items),'direct_complete':sum(x.get('direct_export_status',{}).get('selection')=='complete_final' for x in items.values()),'rag_complete':sum(x['selection']=='rag_complete_final' for x in items.values()),'placeholders':sum(x['selection']!='rag_complete_final' and x['direct_placeholder'] for x in items.values()),'saved_direct':sum(x['selection']=='saved_direct' for x in items.values())}
 if (r/'spawn-error.json').exists():result.update(status='FAILED_START',error=read(r/'spawn-error.json'))
 if result['status']=='RUNNING' and (r/'supervisor.json').exists():
  owner=read(r/'supervisor.json')
  try:alive=ticks(owner['pid'])==owner['ticks']
  except (FileNotFoundError,ProcessLookupError):alive=False
  if not alive:result.update(status='ORPHANED',error='Recorded supervisor ended without terminal receipt; never redispatch automatically')
 engine=r/'package/results/engine/events.jsonl'
 if engine.exists():
  lines=engine.read_text().splitlines(keepends=True)
  if lines and not lines[-1].endswith('\n'):lines=lines[:-1]
  rows=[json.loads(x) for x in lines if x.strip()];result['reserved']=sum(x.get('event')=='reserved' for x in rows);result['completed']=sum(x.get('event')=='completed' for x in rows)
 return result
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('operation',choices=['stage','start','run','status']);ap.add_argument('run_id');ap.add_argument('archive_sha',nargs='?');ap.add_argument('manifest_sha',nargs='?');a=ap.parse_args()
 value=stage(a.run_id,a.archive_sha,a.manifest_sha) if a.operation=='stage' else globals()[a.operation](a.run_id)
 value['ops_sha256']=sha(Path(__file__).resolve())
 print(json.dumps(value))
